# Google Cloud Run configuration for OCR Worker - Production Ready
# Enterprise-grade configuration for B2B PDF processing

runtime: python311

# Enhanced resources for Google Cloud Vision + Document AI processing
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.8

resources:
  cpu: 2
  memory_gb: 4

# Environment variables for production
env_variables:
  # Google Cloud configuration
  GOOGLE_CLOUD_PROJECT: "crafty-tracker-469021-k8"
  # DOCUMENT_AI_PROCESSOR_ID: "your-processor-id-here"  # Optional for Document AI
  
  # Processing limits for B2B documents
  MAX_PDF_SIZE: "104857600"  # 100MB for large B2B docs
  DPI: "200"
  
  # Timeout settings
  PROCESSING_TIMEOUT: "600"  # 10 minutes for complex documents

# Health check
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 1

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 1